### PR TITLE
Fixes toggler in gnome 3.36.1

### PR DESCRIPTION
**Pull request by dipunm**
This will address: https://github.com/Shihira/gnome-extension-quicktoggler/issues/13

Thanks for this extension! :)

### CODE REVIEW

**Comment by dipunm** [comment]
I had to add a try catch inside the `createItem` function, and I found this message:
`Invalid value 'undefined' for property state in object initializer.`

It seems it needs a `true` or `false` value when initialising

**Comment by Shihira** [comment]
Thank you so much or contributing. Please let me know when your patch is completed and ready to merge.

**Comment by dipunm** [comment]
As far as I can tell, this fixed the issue so it should be good to merge.

**Comment by dipunm** [comment]
It's ready to merge @Shihira :)

**Pull request merged**
